// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHO9nxaaP71-KkhGzq48vZ_rFgQWOidIw',
    appId: '1:309355334496:web:7d379c32a1bf006d356c05',
    messagingSenderId: '309355334496',
    projectId: 'flugo-chat-98693',
    authDomain: 'flugo-chat-98693.firebaseapp.com',
    databaseURL: 'https://flugo-chat-98693-default-rtdb.firebaseio.com',
    storageBucket: 'flugo-chat-98693.firebasestorage.app',
    measurementId: 'G-DTP9KNBC4Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtVnj4GP8fLDI_rjr9jzVF1nsTNxUzJzk',
    appId: '1:309355334496:android:1e78f39af4fdb771356c05',
    messagingSenderId: '309355334496',
    projectId: 'flugo-chat-98693',
    databaseURL: 'https://flugo-chat-98693-default-rtdb.firebaseio.com',
    storageBucket: 'flugo-chat-98693.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4qk3PUQPCFtfc-be4ZsXIHY_W9VVCvQE',
    appId: '1:309355334496:ios:275b573d052f342e356c05',
    messagingSenderId: '309355334496',
    projectId: 'flugo-chat-98693',
    databaseURL: 'https://flugo-chat-98693-default-rtdb.firebaseio.com',
    storageBucket: 'flugo-chat-98693.firebasestorage.app',
    iosBundleId: 'com.example.flugoChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4qk3PUQPCFtfc-be4ZsXIHY_W9VVCvQE',
    appId: '1:309355334496:ios:275b573d052f342e356c05',
    messagingSenderId: '309355334496',
    projectId: 'flugo-chat-98693',
    databaseURL: 'https://flugo-chat-98693-default-rtdb.firebaseio.com',
    storageBucket: 'flugo-chat-98693.firebasestorage.app',
    iosBundleId: 'com.example.flugoChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHO9nxaaP71-KkhGzq48vZ_rFgQWOidIw',
    appId: '1:309355334496:web:917a0da4c85a6b57356c05',
    messagingSenderId: '309355334496',
    projectId: 'flugo-chat-98693',
    authDomain: 'flugo-chat-98693.firebaseapp.com',
    databaseURL: 'https://flugo-chat-98693-default-rtdb.firebaseio.com',
    storageBucket: 'flugo-chat-98693.firebasestorage.app',
    measurementId: 'G-0LVQ3LJXMM',
  );
}
